[workspace]
name = "septentrio_gnss_driver"
channels = [
  "http://localhost:8000",
  "https://prefix.dev/robostack-kilted",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
septentrio_gnss_driver = { path = "." }

[package]
name = "septentrio_gnss_driver"
version = "1.5.4"
description = "ROSaic: C++ driver for Septentrio's GNSS and INS receivers"
license = "BSD-3-Clause"
authors = ["Greenroom Robotics <software-team@greenroomrobotics.com>"]

[package.build.backend]
name = "pixi-build-ros-gr"
version = "*"

[package.build.config]
mode = "pixi-native"
build-type = "ament_idl"
distro = "kilted"

[package.host-dependencies]
ros-kilted-ament-cmake               = "*"
ros-kilted-ament-cmake-gtest         = "*"
ros-kilted-rclcpp                    = "*"
ros-kilted-rclcpp-components         = "*"
ros-kilted-rosidl-default-generators = "*"
ros-kilted-diagnostic-msgs           = "*"
ros-kilted-diagnostic-updater        = "*"
ros-kilted-nmea-msgs                 = "*"
ros-kilted-sensor-msgs               = "*"
ros-kilted-geometry-msgs             = "*"
ros-kilted-geographic-msgs           = "*"
ros-kilted-gps-msgs                  = "*"
ros-kilted-nav-msgs                  = "*"
ros-kilted-tf2                       = "*"
ros-kilted-tf2-eigen                 = "*"
ros-kilted-tf2-geometry-msgs         = "*"
ros-kilted-tf2-ros                   = "*"
libboost-devel                       = "*"
libpcap                              = "*"
geographiclib-cpp                    = "*"

[package.run-dependencies]
ros-kilted-rclcpp                    = "*"
ros-kilted-rclcpp-components         = "*"
ros-kilted-rosidl-default-runtime    = "*"
ros-kilted-diagnostic-msgs           = "*"
ros-kilted-diagnostic-updater        = "*"
ros-kilted-nmea-msgs                 = "*"
ros-kilted-sensor-msgs               = "*"
ros-kilted-geometry-msgs             = "*"
ros-kilted-geographic-msgs           = "*"
ros-kilted-gps-msgs                  = "*"
ros-kilted-nav-msgs                  = "*"
ros-kilted-tf2                       = "*"
ros-kilted-tf2-eigen                 = "*"
ros-kilted-tf2-geometry-msgs         = "*"
ros-kilted-tf2-ros                   = "*"
libboost-devel                       = "*"
libpcap                              = "*"
geographiclib-cpp                    = "*"
